tableau-databricks/connection-dialog.tcd, tableau-databricks/connection-resolver.tdr, tableau-databricks/manifest.xml, tableau-databricks/resources-de_DE.xml, tableau-databricks/resources-en_GB.xml, tableau-databricks/resources-en_US.xml, tableau-databricks/resources-es_ES.xml, tableau-databricks/resources-fr_FR.xml, tableau-databricks/resources-it_IT.xml, tableau-databricks/resources-ja_JP.xml, tableau-databricks/resources-ko_KR.xml, tableau-databricks/resources-pt_BR.xml, tableau-databricks/resources-zh_CN.xml, tableau-databricks/resources-zh_TW.xml
When integrating the Databricks conector to Tableau, we made a few changes to the connector:
- We removed the connection-required script and implemented the logic in the xml of the .tdr file to be more performant
- We moved the strings to the resource files for localization. We're doing this for all our connector plugins, although int his case it doesn't look like our loc team felt changes were necessary.
Let me know if you have any questions about the changes.
=> Tableau Changes Handback

tableau-databricks/connection-builder.js
We add a special parameter to let the ODBC driver and Databricks workspace know that it is a connection coming from Tableau.
=> Pass UserAgentEntry client info to ODBC driver

tableau-databricks/connection-resolver.tdr
In preparation for releasing a Databricks-named ODBC driver, we need to add it to the connection resolver.
=> Add Databricks ODBC driver to connection resolver

tableau-databricks/connection-builder.js
This PR uses the SDK to load ODBC connection string extras. ODBC string extras can be configured using instructions from https://community.tableau.com/docs/DOC-23121?_ga=2.220843096.118786453.1581585492-1923689120.1581585492&_fsi=RVazguZ3.
For example, to set proxy settings the `ProxyHost`, `ProxyPort`, `ProxyUID` and `ProxyPWD` extras you need to create a `.tdc` file inside the `My Tableau Repository\Datasources` folder with the content below:
`<connection-customization class='databricks' enabled='true' version='19.1'>
<vendor name='databricks' />
<driver name='databricks' />
<customizations>
<customization name='odbc-connect-string-extras' value='ProxyHost=myproxy.com;ProxyPort=8080;ProxyUID=myuser;ProxyPWD=foo' />
</customizations>
</connection-customization>`
Alternatively, it can be …
=> Load ODBC extras

tableau-databricks/connection-builder.js
This patch allows the connector to passthrough the Spark SQL `spark.sql.crossJoin.enabled` property to the `ThriftServer` which will allow users to create dashboards using EXCLUDE operators without manually setting it on the cluster.
=> Set Simba SSP to passthrough cross join Spark property

tdvt_workspace/results/Tableau_2020_3_test_results.csv
The results are consistent with the 2020.2 results. There is one failure, namely the results for the test case `calcs_data.time1`. This is expected, as Databricks Runtime doesn't support this datatype.
=> Add Tableau 2020.3 test results

tableau-databricks/manifest.xml
The base spark connector issues SHOW VIEWS and SHOW TABLES queries which can be slow. Setting CAP_SUPPRESS_ENUMERATE_TABLES_VIA_SQL suppresses these queries. 
We won't be able to test this until the 2021.1 beta.
=> Add CAP_SUPPRESS_ENUMERATE_TABLES_VIA_SQL to suppress SHOW queries

tableau-databricks/connection-builder.js, tableau-databricks/connection-fields.xml, tableau-databricks/connection-metadata.xml, tableau-databricks/connection-resolver.tdr, tableau-databricks/manifest.xml
Rename the http path field back to 'dbname' for compatibility with the old connector. Using the database field results in the same UX as using the custom field.
Validated through manual testing that an old .tds remains valid.
=> Rename 'v-http-path' -> 'dbname' for backwards compatibility

tableau-databricks/connection-resolver.tdr
Restore the authentication-type attribute as discussed in tableau/connector-plugin-sdk#646
=> Restore authentication-type attribute

tableau-databricks/connection-builder.js
This removes the crossjoin flag permanently, since it's to be phased out in SQL Analytics
=> Remove commented out crossjoin flags

tableau-databricks/manifest.xml
This patch changes the capabilities set at connector level to generate the native SQLGetColumns API call instead of the LIMIT_ZERO query needed to retrieve table metadata.
=> Replace LIMIT_ZERO with SQLGetColumns

tableau-databricks/oauth-config.xml
Our connector was ignoring the instanceurl in the latest release of Tableau's Desktop client 2021.1.0 (20211.21.0320.1853). The symptom was that it would try to form a URL with only a path, e.g. "/authorize".
Tableau seems to have changed the names of these fields in their documentation:
https://tableau.github.io/connector-plugin-sdk/docs/oauth
The cause is that without "OAUTH_CAP_SUPPORTS_CUSTOM_DOMAIN" being set, it will try to use the authUri and tokenUri fields directly.
=> Updating capability key values in OAuth configuration

tableau-databricks/connection-fields.xml, tableau-databricks/oauth-config.xml, tableau-databricks/resources-de_DE.xml, tableau-databricks/resources-en_GB.xml, tableau-databricks/resources-en_US.xml, tableau-databricks/resources-es_ES.xml, tableau-databricks/resources-fr_FR.xml, tableau-databricks/resources-it_IT.xml, tableau-databricks/resources-ja_JP.xml, tableau-databricks/resources-ko_KR.xml, tableau-databricks/resources-pt_BR.xml, tableau-databricks/resources-zh_CN.xml, tableau-databricks/resources-zh_TW.xml
This changes some Microsoft-specific configurations in oauth-config.xml that let us more easily use other IDP providers.
Specifically, it changes the default paths to be more neutral. The tradeoff is that users will need to enter:
https://login.microsoftonline.com/common/oauth2/v2.0
Instead of:
https://login.microsoftonline.com/common
=> Updating OAuth config to allow generic IDP providers

tableau-databricks/connection-fields.xml, tableau-databricks/resources-de_DE.xml, tableau-databricks/resources-en_GB.xml, tableau-databricks/resources-en_US.xml, tableau-databricks/resources-es_ES.xml, tableau-databricks/resources-fr_FR.xml, tableau-databricks/resources-it_IT.xml, tableau-databricks/resources-ja_JP.xml, tableau-databricks/resources-ko_KR.xml, tableau-databricks/resources-pt_BR.xml, tableau-databricks/resources-zh_CN.xml, tableau-databricks/resources-zh_TW.xml
- Change default OAuth endpoint to "Enter address e.g. https://[Server Hostname]/oidc"
- Change OAuth label in dropdown to "OAuth / Azure AD"
- Change OAuth field header to "OAuth Endpoint"
- Add validator for OAuth Endpoint to restrict to "https://[hostname]/oidc"
=> Improve OAuth labels and fields

tableau-databricks/dialect.tdd
Implement the Tableau CONTAINS expression as INSTR() instead of the
current use of RLIKE(*.*). The INSTR SQL expression is implemented more
efficiently than RLIKE().
=> Use SQL INSTR() for CONTAINS expressions

tableau-databricks/dialect.tdd
Tableau's XML checker enforces that all `function`s should be defined before `date-function`s.
=> Move CONTAINS function next to other functions

tableau-databricks/connection-builder.js
This patch adds two Simba configuration that prevent the driver from 
1) turning server-side properties to lower-case
2) setting the properties by executing statements
=> Add Simba SSP configurations

tableau-databricks/connection-fields.xml, tableau-databricks/resources-de_DE.xml, tableau-databricks/resources-en_GB.xml, tableau-databricks/resources-en_US.xml, tableau-databricks/resources-es_ES.xml, tableau-databricks/resources-fr_FR.xml, tableau-databricks/resources-it_IT.xml, tableau-databricks/resources-ja_JP.xml, tableau-databricks/resources-ko_KR.xml, tableau-databricks/resources-pt_BR.xml, tableau-databricks/resources-zh_CN.xml, tableau-databricks/resources-zh_TW.xml
- Remove the default value from the OAuth endpoint field, since it's invalid anyway.
- Change to OAuth field header to "OAuth Endpoint e.g. https://[Server Hostname]/oidc"
- Allow the entry of Databricks redirector URLs as well as AAD endpoints.
=> Change OAuth field header and allow AAD endpoints

tableau-databricks/oauth-config.xml
Upon Tableau's request, set OAUTH_CAP_REQUIRES_PROMPT_SELECT_ACCOUNT=true
=> Set capability OAUTH_CAP_REQUIRES_PROMPT_SELECT_ACCOUNT=true

tableau-databricks/oauth-config.xml
This is to make it consistent with the regex from the connection
dialog. Otherwise, certain URLs e.g. https://servername/oidc pass in
the connection dialog but fail when attempting to connect.
=> Remove trailing slash from instanceUrlValidationRegex

tableau-databricks/connection-builder.js
This patch removes setting the `SSP_databricks.catalog` configuration as a backwards compatible fix for integrations that use ODBC drivers without multi-catalog support.
=> Remove  passing through `SSP_databricks.catalog` to ODBC

tableau-databricks/oauth-config.xml
The OAuth clientId used in the prepackaged Tableau connector is different from the one in our repo currently. This PR makes repo connector consistent with the production connector.
=> Switch to production OAuth clientId

tableau-databricks/manifest.xml
Verified locally that cross database join works with the capability set, see steps here: https://docs.google.com/document/d/1axL5YE1_vZsejvK9QksjOGxiUjnZpe0k33PPeU3WLFQ/edit?usp=sharing.
1. run tdvt tests, results same as before
2. Test backward compatibility, new connector can open old joined workbook, old connector can open new joined workbook so both way works fine.
=> enable cross database join in single connection

tableau-databricks/manifest.xml
There's a leading whitespace in  name=' CAP_ODBC_INCLUDE_CATALOG_NAME' which should not be there.
=> Remove leading whitespace

tableau-databricks/connection-fields.xml, tableau-databricks/oauth-config.xml
Adding the auto infer oauth instanceUrl capability to Databricks.
The new UI will look like this:(ignore the databricks2 by Company Name part)
Old UI looks like this:
Testing:
Locally test with Tableau Desktop. Open old Workbook with this new connector works, open new workbook with old connector works.
Tableau Server has not released 2023.2 so cannot test there yet.
=> add auto infer instanceUrl

tableau-databricks/manifest.xml
From Tableau: `The fact that you have both CAP_ODBC_METADATA_SUPPRESS_PREPARED_QUERY and CAP_ODBC_METADATA_SUPPRESS_EXECUTED_QUERY set to yes means that CAP_QUERY_TOP_0_METADATA will only be used during Custom SQL.`
The purpose of this change is for a custom sql query it currently use select * limit 1 to get metadata, but it can take a long time if the custom query is complex. We can use limit 0 to expedite the get metadata operation.
This should not affect metadata fetching for a regular table, those will still use the built in odbc functions to retrieve metadata.
**Test Matrix:**
Spark Versions: 9.1, 10.4. 11.3, 12.2, 13.3, 14.1
Unity Catalog: True, False
**Test Step:** 
Create Tableau connection
Create a new Custom Sql query: Select * from `schema`.`table`
Verify metadata renders …
=> Enable the CAP_QUERY_TOP_0_METADATA capability for custom SQL queries

tableau-databricks/resources-de_DE.xml, tableau-databricks/resources-en_GB.xml, tableau-databricks/resources-en_US.xml, tableau-databricks/resources-es_ES.xml, tableau-databricks/resources-fr_FR.xml, tableau-databricks/resources-it_IT.xml, tableau-databricks/resources-ja_JP.xml, tableau-databricks/resources-ko_KR.xml, tableau-databricks/resources-pt_BR.xml, tableau-databricks/resources-zh_CN.xml, tableau-databricks/resources-zh_TW.xml
As part of effort to promote OAuth usage we want to slowly deprecate other auth modes in Tableau. 
As a first step we are changing the auth mode text to denote what is recommend/deprecated.
Databricks login (recommended) is the OAuth login.
Basic auth (deprecated) is the username-password.
The risk is minimal since it only changes the label shown to customer.
Get approval from Slack from: @sbhaiatdb and @ken wong
=> recommend oauth

tableau-databricks/connection-fields.xml
Remove the basic auth mode from Tableau connector
=> [PECO-1754]remove basic auth from Tableau connector

tableau-databricks/resources-en_US.xml
Now that we are removing the username/password auth mode, there is no need to keep labeling the password field as password. We can call it token, because people will be pasting their token in.
If this change is accepted, will make the change on our side as a follow-up to the change that removes username/password auth.
=> Change "Password" Label to "Token"
